// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// encodeC
std::string encodeC(IntegerVector num, List settings);
RcppExport SEXP hashids_encodeC(SEXP numSEXP, SEXP settingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type num(numSEXP);
    Rcpp::traits::input_parameter< List >::type settings(settingsSEXP);
    __result = Rcpp::wrap(encodeC(num, settings));
    return __result;
END_RCPP
}
