# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Encodes an integer or integer vector into a hashid string.
#' All numbers must be non-negative integers.
#'
#' @param int Integer or integer vector to encode
#' @param settings Settings list generated by hashid_settings
#' @return hashid string
#' @export
encodeC <- function(num, settings) {
    .Call('hashids_encodeC', PACKAGE = 'hashids', num, settings)
}

